name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

#      - name: Install golangci-lint
#        uses: golangci/golangci-lint-action@v3
#        with:
#          version: latest

#      - name: Run linter
#        run: golangci-lint run --config githooks/.golangci.yaml --issues-exit-code 0

      - name: Build
        run: go build -v ./...

#      - name: Test
#        run: go test -v ./...